In [1]:
import os

os.chdir('/home/enis/projects/nna/src/nna/exp/megan/run-1/')


In [2]:
import run
import nna
import numpy as np

In [3]:
audio_dataset,_ = prepare_dataset()

Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable
wandb: Wandb version 0.10.12 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
/scratch/enis/data/nna/labeling/megan/AudioSamplesPerSite/meganLabeledFiles_wlenV1.txt
/scratch/enis/data/nna/labeling/megan/AudioSamplesPerSite
4 files are missing corresponding to excell entries
'-> 5 number of samples are DELETED due to ignore_files and missing_audio_files'
-> 415 samples DELETED because they are not in the excell

-> 0 samples DELETED because they do not have the taxo info coming from excell

-> classes that do not have enough data:
[REMOVED!]
['other-mammal'] 0.0
['other-silence'] 20.0
['unknown-sound'] 2.0
['seabirds'] 1.0
['canids'] 1.0
['other-flare'] 11.0
['other-rain'] 20.0

-> classes that have enough data:
['other-biophony'] 56.0
['other-insect'] 140.0
['other-bird'] 661.0
['songbirds'] 392.0
['duck-goose-swan'] 183.0
['grouse-ptarmigan'] 59.0
['

In [4]:
output_file_path = '/scratch/enis/data/nna/labeling/megan/AudioSamplesPerSite/files_as_np_filtered_v3_int16.pkl'
# audio_dataset.load_audio_files(cached_dict_path=output_file_path)



In [5]:
#performance tests of loading files
# %%time # 75 seconds
# audio_dataset.load_audio_files()
# %%time # 42 second
# audio_dataset.load_audio_files(cached_dict_path=output_file_path)

In [6]:
# # save files # first time
# audio_dataset.load_audio_files()
# audio_dataset.pick_channel_by_clipping()
# audio_dataset.create_cache_pkl(output_file_path)

In [7]:
# just load
audio_dataset.load_audio_files(output_file_path)
audio_dataset.pick_channel_by_clipping()

In [9]:
for key, value in audio_dataset.items():
    # data = cached_dict.get(str(value.path), None)
    print(value.data.shape)
    break

(1045414,)


In [16]:
str(value.path)

'/scratch/enis/data/nna/labeling/megan/AudioSamplesPerSite/Site_11/SP1/S4A10276_20190710_091602_Bio_01.wav'

In [17]:
for k, v in cached_dict.items():
    print(type(k),k,v[0].shape)
    break

<class 'pathlib.PosixPath'> /scratch/enis/data/nna/labeling/megan/AudioSamplesPerSite/Site_11/SP1/S4A10276_20190710_091602_Bio_01.wav (1045414,)


In [68]:
from pathlib import Path
data_file = {}
if Path(output_file_path).exists():
    raise ValueError(f'{output_file_path} already exists')
for k, v in audio_dataset.items():
    data_file[k] = v.data[:], v.sr


In [73]:
d=iter(data_file.values())

In [75]:
next(d)

(array([-4073., -4064., -4047., ..., -7174., -7237., -7305.]), 48000)

In [74]:
for v in data_file.values():
    if len(v[0].shape)>1:
        print(v.shape)

In [76]:
with open(output_file_path, 'wb') as f:
    np.save(f, data_file)

In [14]:
b=iter(audio_dataset.values())

In [8]:
a=next(b)
a.clipping,a.length,a.data.shape

(array([[0.        , 0.00509167],
        [0.00678958, 0.02112917],
        [0.        , 0.0131126 ]]),
 21.779458,
 (2, 1045414))

In [11]:
a=next(b)
a.clipping,a.length,a.data.shape

(array([[0.        , 0.00509167],
        [0.00678958, 0.02112917],
        [0.        , 0.0131126 ]]),
 21.779458,
 (1045414,))

In [42]:
a=next(b)
a.clipping,a.length,a.data.shape

(array([[0.00106042, 0.00228542],
        [0.        , 0.        ]]),
 12.391771,
 (594805,))

In [8]:
a=next(b)
a.clipping,a.length,a.data.shape

(array([[0.        , 0.00509167],
        [0.00678958, 0.02112917],
        [0.        , 0.0131126 ]]),
 21.779458,
 (2, 1045414))

In [18]:
# from pydub import AudioSegment
# import numpy as np

In [5]:
device = torch.device(
    f"cuda:{config.device}" if torch.cuda.is_available() else "cpu")


In [22]:
from pathlib import Path
import numpy as np
from sklearn.model_selection import train_test_split

# labelsbyhumanpath = Path('/scratch/enis/data/nna/labeling/results/')
# sourcePath = Path("/scratch/enis/data/nna/labeling/splits/")


In [23]:
 # RAW DATA
 def load_raw_data(labelsbyhumanpath,sourcePath):
    # load labels for data
    with open(labelsbyhumanpath/"np_array_Ymatrix.npy", 'rb') as f:
        y_true = np.load(f)
    
        # ## load Dataset
        # # X.shape is (1300, 10, 44100)
    with open(sourcePath/"np_array_Xmatrix_shortby441000.npy", 'rb') as f:
        X = np.load(f)
        #
        # ### split data
    X_train, X_test, y_train, y_test = train_test_split(
                    X, y_true, test_size=0.2, random_state=42)
    X_train, X_val, y_train, y_val = train_test_split(
                    X_train, y_train, test_size=0.25, random_state=42)
    return X_train,X_test,X_val,y_train,y_test,y_val

    

In [24]:
X_train,X_test,X_val,y_train,y_test,y_val = load_raw_data(labelsbyhumanpath,sourcePath)

In [25]:
X_train.shape

(780, 10, 44100)

In [ ]:
    # RAW DATA
    # load labels for data
    # with open(labelsbyhumanpath/"np_array_Ymatrix.npy", 'rb') as f:
    #     y_true = np.load(f)
    #
    #     # ## load Dataset
    #     # # X.shape is (1300, 10, 44100)
    # with open(sourcePath/"np_array_Xmatrix_shortby441000.npy", 'rb') as f:
    #     X = np.load(f)
    #     #
    #     # ### split data
    # X_train, X_test, y_train, y_test = train_test_split(
    #                 X, y_true, test_size=0.2, random_state=42)
    # X_train, X_val, y_train, y_val = train_test_split(
    #                 X_train, y_train, test_size=0.25, random_state=42)
    #

    ##### AUGMENTATIONS #######

    # ###### randomADD
    # X_trainAugmented,y_trainAugmented = augmentations.randomAdd(X_train,y_train,config["augmentadSize"],unique=False)
    # X_train = X_trainAugmented
    # y_train = y_trainAugmented
    # # to keep original ones in the same shape
    # # increase size of original ones by merging them with themselves or we could just use augmentad ones
    #
    # ########### calculate mel-spectogram for all data
    #
    # XArrays=[X_val,X_test,X_train]
    # X_val,X_test,X_train=runUtils.clipped_mel_loop(XArrays,850)
    #
    #     # # add channel dimension and turn data into float32
    # XArrays=[X_train,X_test,X_val]
    # for i,X_array in enumerate(XArrays):
    #     XArrays[i]=X_array.reshape(X_array.shape[0],1,*X_array.shape[1:])
    #
    # [X_train,X_test,X_val]=XArrays

    # AUGMENTED ONES
    # with open(sourcePath/"np_array_Xmatrix_addAug_mel.npy", 'rb') as f:
    #     XArrays = pickle.load(f)
    #     [X_train,X_test,X_val]=XArrays
    # with open(sourcePath/"np_array_Ymatrix_seperate.npy", 'rb') as f:
    #     yArrays = pickle.load(f)
    #     [y_train,y_test,y_val]=yArrays